"""Curated list of popular WikiVoyage destinations for ingestion."""

DESTINATIONS: list[dict[str, str]] = [
    {"city": "Cancun", "country": "Mexico", "iata": "CUN", "wikivoyage_slug": "Cancun"},
    {"city": "Barcelona", "country": "Spain", "iata": "BCN", "wikivoyage_slug": "Barcelona"},
    {"city": "Paris", "country": "France", "iata": "CDG", "wikivoyage_slug": "Paris"},
    {"city": "Rome", "country": "Italy", "iata": "FCO", "wikivoyage_slug": "Rome"},
    {"city": "London", "country": "United Kingdom", "iata": "LHR", "wikivoyage_slug": "London"},
    {"city": "Tokyo", "country": "Japan", "iata": "NRT", "wikivoyage_slug": "Tokyo"},
    {"city": "Bangkok", "country": "Thailand", "iata": "BKK", "wikivoyage_slug": "Bangkok"},
    {"city": "Bali", "country": "Indonesia", "iata": "DPS", "wikivoyage_slug": "Bali"},
    {"city": "Istanbul", "country": "Turkey", "iata": "IST", "wikivoyage_slug": "Istanbul"},
    {"city": "Athens", "country": "Greece", "iata": "ATH", "wikivoyage_slug": "Athens"},
    {"city": "Lisbon", "country": "Portugal", "iata": "LIS", "wikivoyage_slug": "Lisbon"},
    {"city": "Madrid", "country": "Spain", "iata": "MAD", "wikivoyage_slug": "Madrid"},
    {"city": "Miami", "country": "United States", "iata": "MIA", "wikivoyage_slug": "Miami"},
    {"city": "New York City", "country": "United States", "iata": "JFK", "wikivoyage_slug": "New_York_City"},
    {"city": "Los Angeles", "country": "United States", "iata": "LAX", "wikivoyage_slug": "Los_Angeles"},
    {"city": "Lima", "country": "Peru", "iata": "LIM", "wikivoyage_slug": "Lima"},
    {"city": "Buenos Aires", "country": "Argentina", "iata": "EZE", "wikivoyage_slug": "Buenos_Aires"},
    {"city": "Santiago de Chile", "country": "Chile", "iata": "SCL", "wikivoyage_slug": "Santiago_de_Chile"},
    {"city": "Bogota", "country": "Colombia", "iata": "BOG", "wikivoyage_slug": "Bogota"},
    {"city": "Cartagena", "country": "Colombia", "iata": "CTG", "wikivoyage_slug": "Cartagena_(Colombia)"},
    {"city": "Havana", "country": "Cuba", "iata": "HAV", "wikivoyage_slug": "Havana"},
    {"city": "Punta Cana", "country": "Dominican Republic", "iata": "PUJ", "wikivoyage_slug": "Punta_Cana"},
    {"city": "San Juan", "country": "Puerto Rico", "iata": "SJU", "wikivoyage_slug": "San_Juan_(Puerto_Rico)"},
    {"city": "Panama City", "country": "Panama", "iata": "PTY", "wikivoyage_slug": "Panama_City"},
    {"city": "Mexico City", "country": "Mexico", "iata": "MEX", "wikivoyage_slug": "Mexico_City"},
    {"city": "Quito", "country": "Ecuador", "iata": "UIO", "wikivoyage_slug": "Quito"},
    {"city": "Maldives", "country": "Maldives", "iata": "MLE", "wikivoyage_slug": "Maldives"},
    {"city": "Dubai", "country": "UAE", "iata": "DXB", "wikivoyage_slug": "Dubai"},
    {"city": "Singapore", "country": "Singapore", "iata": "SIN", "wikivoyage_slug": "Singapore"},
    {"city": "Seoul", "country": "South Korea", "iata": "ICN", "wikivoyage_slug": "Seoul"},
    {"city": "Amsterdam", "country": "Netherlands", "iata": "AMS", "wikivoyage_slug": "Amsterdam"},
    {"city": "Prague", "country": "Czech Republic", "iata": "PRG", "wikivoyage_slug": "Prague"},
    {"city": "Montego Bay", "country": "Jamaica", "iata": "MBJ", "wikivoyage_slug": "Montego_Bay"},
    {"city": "Sao Paulo", "country": "Brazil", "iata": "GRU", "wikivoyage_slug": "S\u00e3o_Paulo"},
    {"city": "San Jose", "country": "Costa Rica", "iata": "SJO", "wikivoyage_slug": "San_Jos\u00e9_(Costa_Rica)"},
]
